### ISSUE TITLE
`Add-WorkspaceOneDirectory` fails with "Set-WSABindPassword : The remote server returned an error: (400) Bad Request."

### ISSUE THREAD

**Issue by cybernils** [vmware-samples/power-validated-solutions-for-cloud-foundation#224] opened 2023-03-14 12:53 UTC
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.0

### Module Version

2.0.0.1010

### PowerShell Version

5.1.19041.2364

### PowerCLI Version

12.7.0

### PowerVCF Version

2.2.0

### Guest Operating System

Windows 10

### Description

```powershell
Set-WSABindPassword : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:925 char:25
+ ...             Set-WSABindPassword -directoryId $directory.directoryConf ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSABindPassword
Set-WSADirectoryUser : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:962 char:25
+ ...             Set-WSADirectoryUser -directoryId $directory.directoryCon ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSADirectoryUser
Set-WSADirectoryGroup : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:963 char:25
+ ...             Set-WSADirectoryGroup -directoryId $directory.directoryCo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSADirectoryGroup
Set-WSASyncSetting : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:964 char:25
+ ...             Set-WSASyncSetting -directoryId $directory.directoryConfi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSASyncSetting
Start-WSADirectorySync : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:965 char:25
+ ...             Start-WSADirectorySync -directoryId $directory.directoryC ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Start-WSADirectorySync
```

### Error or Debug Output

```powershell
Set-WSABindPassword : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:925 char:25
+ ...             Set-WSABindPassword -directoryId $directory.directoryConf ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSABindPassword
Set-WSADirectoryUser : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:962 char:25
+ ...             Set-WSADirectoryUser -directoryId $directory.directoryCon ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSADirectoryUser
Set-WSADirectoryGroup : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:963 char:25
+ ...             Set-WSADirectoryGroup -directoryId $directory.directoryCo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSADirectoryGroup
Set-WSASyncSetting : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:964 char:25
+ ...             Set-WSASyncSetting -directoryId $directory.directoryConfi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSASyncSetting
Start-WSADirectorySync : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:965 char:25
+ ...             Start-WSADirectorySync -directoryId $directory.directoryC ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Start-WSADirectorySync
```

### Expected Behavior

Directory and Identity Provider to be added.

### Actual Behavior

Only the Directory is added, not the Identity Provider.

### Steps to Reproduce

```powershell
Add-WorkspaceOneDirectory -server $wsaFqdn -user admin -pass $wsaAdminPassword -domain $domainFqdn -baseDnUser $baseDnUsers -baseDnGroup $baseDnGroups -bindUserDn $wsaBindUserDn -bindUserPass $wsaBindUserPassword -adGroups $adGroups -protocol ldaps
````

The following three manual steps have been tested:

```powershell
$directory = Add-WSALdapDirectory -domainName $domain -baseDn $baseDnUser -bindDn $bindUserDn -certificate $certificate

$connector = Get-WSAConnector | Where-Object {$_.host -eq $server}

Set-WSABindPassword -directoryId $directory.directoryConfigId -connectorId $connector.instanceId -pass $bindUserPass
```
The first two steps succeed, while the third step fails:

```powershell
PS E:\> Set-WSABindPassword -directoryId $directory.directoryConfigId -connectorId $connector.instanceId -pass $wsaBindUserPassword
Set-WSABindPassword : The remote server returned an error: (400) Bad Request.
At line:1 char:1
+ Set-WSABindPassword -directoryId $directory.directoryConfigId -connec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-WSABindPassword
```

**Comment by tenthirtyam** [comment] 2023-03-14 12:55
I've applied code formatting to the issue description for readability.

**Comment by GaryJBlake** [comment] 2023-05-15 07:39
Unable to reproduce in our lab

**Comment by tenthirtyam** [comment] 2023-07-15 01:38
@GaryJBlake I wonder if this is similar to #262?

**Comment by GaryJBlake** [comment] 2023-07-17 09:35
Following applying changes under https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/294 I've tested this again and still not seeing any issues. We are running pipelines this week using the latest build of the code so will await the outcome.

**Comment by GaryJBlake** [comment] 2023-07-23 06:36
Unable to reproduce this issue, pipelines executed on 4.5.1 and 5.0.0 and also not seen issue. Next week we will be releasing 2.5.0 of this module and as this issue was originally flagged using 2.2.0 I'm going to Close this issue.

If you see this issue in the future please feel free to re-open this issue and provide additional information.

**Closed by GaryJBlake** 2023-07-23 06:36 UTC
Labels: bug, not-reproduced
